version: '3.8'

services:
  spring-app:
    image: lhj0430/final:latest
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://ahi-mysql.c1i2m6swi0dl.ap-northeast-2.rds.amazonaws.com:3306/timecapsule
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=ormi5ahi!!!
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
    networks:
      - mynetwork
    depends_on:
      - redis

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - mynetwork
    volumes:
      - redis-data:/data

networks:
  dist_mynetwork:

volumes:
  redis-data:
